In [1]:
import pandas as pd
df = pd.read_csv("C:/Users/Trang Ha/Documents/Data_Game/mobile_game.csv")
df.head()

,UserID,Age,Gender,Country,Device,GameGenre,SessionCount,AverageSessionLength,SpendingSegment,InAppPurchaseAmount,FirstPurchaseDaysAfterInstall,PaymentMethod,LastPurchaseDate
0,c9889ab0-9cfc-4a75-acd9-5eab1df0015c,49.0,Male,Norway,Android,Battle Royale,9,12.83,Minnow,11.40,28.0,Apple Pay,2025-03-19
1,7c9e413c-ecca-45f2-a780-2826a07952a2,15.0,Male,Switzerland,iOS,Action RPG,11,19.39,Minnow,6.37,18.0,Debit Card,2025-06-08
2,fd61e419-1a92-4f43-a8c7-135842ad328a,23.0,Male,China,Android,Fighting,9,8.87,Minnow,15.81,30.0,Apple Pay,2025-06-02
3,bdb7f6d1-ff9a-468c-afe7-43f32a94293e,31.0,Male,Mexico,Android,Racing,12,19.56,Minnow,13.49,9.0,Debit Card,2025-04-01
4,aa7eec14-4846-47b9-b879-9c98038cda04,37.0,Female,India,Android,Battle Royale,10,15.23,Minnow,10.86,15.0,Paypal,2025-05-05

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2888 entries, 0 to 2887
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   UserID                         2888 non-null   str
 1   Age                            2835 non-null   float64
 2   Gender                         2829 non-null   str
 3   Country                        2828 non-null   str
 4   Device                         2832 non-null   str
 5   GameGenre                      2831 non-null   str
 6   SessionCount                   2888 non-null   int64
 7   AverageSessionLength           2888 non-null   float64
 8   SpendingSegment                2888 non-null   str
 9   InAppPurchaseAmount            2888 non-null   float64
 10  FirstPurchaseDaysAfterInstall  2888 non-null   float64
 11  PaymentMethod                  2888 non-null   str
 12  LastPurchaseDate               2888 non-null   str
dtypes: float64(4), int64(1), str(8)
memory usage: 293.4 KB

In [4]:
df.isnull().sum()

UserID                            0
Age                              53
Gender                           59
Country                          60
Device                           56
GameGenre                        57
SessionCount                      0
AverageSessionLength              0
SpendingSegment                   0
InAppPurchaseAmount               0
FirstPurchaseDaysAfterInstall     0
PaymentMethod                     0
LastPurchaseDate                  0
dtype: int64

In [5]:
df['UserID'].duplicated().sum()

np.int64(0)

In [6]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [7]:
df['Gender'] = df['Gender'].fillna('Unknown')
df['Country'] = df['Country'].fillna('Unknown')
df['Device'] = df['Device'].fillna('Unknown')
df['GameGenre'] = df['GameGenre'].fillna('Unknown')

In [8]:
df['LastPurchaseDate'] = pd.to_datetime(
    df['LastPurchaseDate'],
    errors='coerce'
)
type(df['LastPurchaseDate'].dtype)

numpy.dtypes.DateTime64DType

In [9]:
df.groupby('SpendingSegment')['InAppPurchaseAmount'].agg(
    ['count', 'min', 'max', 'mean', 'sum']
)

                 count     min      max         mean        sum
SpendingSegment
Dolphin            392   20.53   497.91   245.634694   96288.80
Minnow            2433    0.00    20.00    10.023580   24387.37
Whale               63  608.21  4964.45  2787.033968  175583.14

In [10]:

df[
    df['InAppPurchaseAmount'].isin([20, 500])
][
    ['InAppPurchaseAmount', 'SpendingSegment']
]

      InAppPurchaseAmount SpendingSegment
1218                 20.0          Minnow
2731                 20.0          Minnow

In [11]:
df.describe()

,Age,SessionCount,AverageSessionLength,InAppPurchaseAmount,FirstPurchaseDaysAfterInstall,LastPurchaseDate
count,2888.000000,2888.000000,2888.000000,2888.000000,2888.000000,2888
mean,33.483380,10.066828,20.076250,102.582864,15.384003,2025-04-24 16:33:14.459833
min,13.000000,1.000000,5.010000,0.000000,0.000000,2025-01-01 00:00:00
25%,24.000000,8.000000,12.630000,5.987500,8.000000,2025-02-28 00:00:00
50%,33.000000,10.000000,20.325000,11.975000,16.000000,2025-04-26 00:00:00
75%,43.000000,12.000000,27.432500,17.762500,23.000000,2025-06-20 00:00:00
max,54.000000,22.000000,34.990000,4964.450000,30.000000,2025-08-13 00:00:00
std,11.853382,3.121936,8.602216,454.339708,8.946191,NaN

In [14]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

connection_string = (
    r"DRIVER={ODBC Driver 17 for SQL Server};"
    r"SERVER=localhost\SQLEXPRESS;"
    "DATABASE=mobile_game;"
    "Trusted_Connection=yes;"
)

engine = create_engine(
    "mssql+pyodbc:///?odbc_connect=" + quote_plus(connection_string)
)

df.to_sql("mobile_game_data",engine, if_exists="replace", index=False)

151